# Generated by Django 3.2.11 on 2022-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestioncomment',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='suggestionvote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='suggestionvote',
            name='suggestion',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='SuggestionComment',
        ),
        migrations.DeleteModel(
            name='SuggestionVote',
        ),
    ]
